export const data = [
  { id: 81, name: "snareon4", src: "../audio/SnareOn4.wav", title: "Q" },
  { id: 89, name: "metallic2", src: "../audio/Metallic2.wav", title: "W" },
  { id: 69, name: "kick", src: "../audio/Kick.wav", title: "E" },
  { id: 82, name: "snareon5", src: "../audio/SnareOn5.wav", title: "R" },
  { id: 84, name: "tom", src: "../audio/Tom.wav", title: "T" },
  { id: 87, name: "analague", src: "../audio/Analague.wav", title: "Y" },
  { id: 85, name: "tom2", src: "../audio/Tom2.wav", title: "U" },
  { id: 73, name: "kick4", src: "../audio/Kick4.wav", title: "I" },
  { id: 79, name: "snareon2", src: "../audio/SnareOn2.wav", title: "O" },
  { id: 80, name: "snareon3", src: "../audio/SnareOn3.wav", title: "P" },
  { id: 65, name: "hihat", src: "../audio/HiHat.wav", title: "A" },
  { id: 83, name: "snareon6", src: "../audio/SnareOn6.wav", title: "S" },
  { id: 68, name: "hihat3", src: "../audio/HiHat3.wav", title: "D" },
  { id: 70, name: "snares2", src: "../audio/Snares_061.wav", title: "F" },
  { id: 71, name: "kick3", src: "../audio/Kick3.wav", title: "G" },
  { id: 72, name: "kick2", src: "../audio/Kick2.wav", title: "H" },
  { id: 74, name: "kick5", src: "../audio/Kick5.wav", title: "J" },
  { id: 75, name: "kick6", src: "../audio/Kick6.wav", title: "K" },
  { id: 76, name: "mallet", src: "../audio/Mallet.wav", title: "L" },
  { id: 90, name: "snares", src: "../audio/Snares.wav", title: "Z" },
  { id: 88, name: "metallic", src: "../audio/Metallic.wav", title: "X" },
  { id: 67, name: "hihat2", src: "../audio/HiHat2.wav", title: "C" },
  { id: 86, name: "tom3", src: "../audio/Tom3.wav", title: "V" },
  { id: 66, name: "snares1", src: "../audio/Snares_050.wav", title: "B" },
  { id: 78, name: "snareon", src: "../audio/SnareOn.wav", title: "N" },
  { id: 77, name: "metal", src: "../audio/Metal.wav", title: "M" },
];
